# syntax=docker/dockerfile:1

FROM golang:1.24-alpine AS builder

RUN apk add --no-cache vips-dev build-base pkgconfig
ENV CGO_ENABLED=1 PKG_CONFIG_PATH=/usr/lib/pkgconfig
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download


COPY . .
RUN go build -o server .

FROM alpine:3.20
RUN apk add --no-cache vips ca-certificates
WORKDIR /app
COPY --from=builder /app/server .
COPY --from=builder /app/static ./static/
COPY --from=builder /app/templates ./templates/

EXPOSE 3000

CMD ["./server"]