# syntax=docker/dockerfile:1

FROM golang:1.24.3 AS builder

WORKDIR /app
ENV CGO_ENABLED=0
COPY . .

RUN go mod tidy
RUN go build -o server .

FROM alpine

WORKDIR /app
COPY --from=builder /app/server .
COPY --from=builder /app/static ./static/
COPY --from=builder /app/templates ./templates/

EXPOSE 3000

CMD ["./server"]